from PyQt5.QtWidgets import QComboBox
from sqlite3 import Connection
from typing import List


class DBUtils:
    def __init__(self, projDir: str, projName: str, dbProjTemplate: str, dbRefTemplate: str, isBatch: bool) -> None: ...
    def hashDbTable(self, conn: Connection, table: str) -> str: ...
    def importCsv(self, table: str, typ: str, fil: str) -> str: ...
    def populateTableNames(self) -> None: ...
    def populateUsersoilTableNames(self, comboBox: QComboBox) -> None: ...
    def readCsvFile(self, csvFile: str, typ: str, names: List[str]) -> str: ...
    @staticmethod
    def sqlSelect(table: str, selection: str, order: str, where: str) -> str: ...
